jsf:
  PROJECT_STAGE: Production
  primefaces:
    theme: omega
    
joinfaces:
  version: 3.2.3
spring-boot:
  version: 2.0.3.RELEASE
tomcat:
  version: 8.5.31
jetty:
  version: 9.4.11.v20180605
undertow:
  version: 1.4.25.Final
cdi:
  version: 2.0
mojarra:
  version: 2.3.5
myfaces:
  version: 2.3.1
omnifaces:
  version: 1.14.1
angularfaces:
  version: 2.1.12
primefaces:
  version: 6.2
primefaces-extensions:
  version: 6.2.4
bootsfaces:
  version: 1.2.0
butterfaces:
  version: 3.0.2
richfaces:
  version: 4.5.17.Final

spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.8.123:1522/vuceca01.vuce.gob.pe
    username: mtapp
    password: mtapp

server:
  port: 9005 