  CREATE OR REPLACE PROCEDURE "MTSRC"."HABILITAR_TRANSMISIONES" 
(
  VE_ID IN NUMBER 
, RESULTADO_VALOR OUT NUMBER 
, RESULTADO_MENSAJE OUT VARCHAR2 
) AS 
BEGIN
   RESULTADO_VALOR := 0;
  RESULTADO_MENSAJE := 'la transmisión ' || VE_ID || ' fue habilitada correctamente';
END HABILITAR_TRANSMISIONES;
/

