--------------------------------------------------------
-- Archivo creado  - martes-diciembre-04-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONFIGURACION
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."CONFIGURACION" 
   (    "LLAVE" VARCHAR2(20 BYTE), 
    "VALOR" VARCHAR2(100 BYTE)) 
--   ) SEGMENT CREATION IMMEDIATE 
--  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Table ENTIDAD
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."ENTIDAD" 
   (    "ID_ENTIDAD" NUMBER, 
    "ENTIDAD" VARCHAR2(10 BYTE), 
    "NOMBRE_ENTIDAD" VARCHAR2(50 BYTE), 
    "CORREO_SOPORTE" VARCHAR2(100 BYTE), 
    "SLA_DISPONIBILIDAD_TRANSACCION" NUMBER, 
    "SLA_CONFIRMACION_TRANSACCION" NUMBER, 
    "SLA_PROCESAMIENTO_NOTIFICACION" NUMBER, 
    "SLA_FRECUENCIA_LECTURA" NUMBER, 
    "SLA_FRECUENCIA_LECTURA_PM" NUMBER) 
--   ) SEGMENT CREATION IMMEDIATE 
/*  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;

   COMMENT ON COLUMN "MTOBJ"."ENTIDAD"."SLA_DISPONIBILIDAD_TRANSACCION" IS 'en minutos';
   COMMENT ON COLUMN "MTOBJ"."ENTIDAD"."SLA_CONFIRMACION_TRANSACCION" IS 'en minutos';
   COMMENT ON COLUMN "MTOBJ"."ENTIDAD"."SLA_PROCESAMIENTO_NOTIFICACION" IS 'en minutos';
   COMMENT ON COLUMN "MTOBJ"."ENTIDAD"."SLA_FRECUENCIA_LECTURA" IS 'en minutos';
   COMMENT ON COLUMN "MTOBJ"."ENTIDAD"."SLA_FRECUENCIA_LECTURA_PM" IS 'en minutos';
--------------------------------------------------------
--  DDL for Table ENTIDADMANTENIMIENTO
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."ENTIDADMANTENIMIENTO" 
   (    "ID_ENTIDAD" NUMBER, 
    "FECHA_INICIO" DATE, 
    "FECHA_FIN" DATE, 
    "ID_ENTIDAD_MANTENIMIENTO" NUMBER)
--   ) SEGMENT CREATION IMMEDIATE 
--  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_DAT" ;

   COMMENT ON COLUMN "MTOBJ"."ENTIDADMANTENIMIENTO"."FECHA_INICIO" IS 'fecha y hora del inicio del manteinimiento';
   COMMENT ON COLUMN "MTOBJ"."ENTIDADMANTENIMIENTO"."FECHA_FIN" IS 'fecha y hora del fin del mantenimiento';
--------------------------------------------------------
--  DDL for Table PERIODO_MONITOREO
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."PERIODO_MONITOREO" 
   (    "HORA" VARCHAR2(20 BYTE)) 
--   ) SEGMENT CREATION IMMEDIATE 
/*  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Table RECEPCIONTRANSACCION
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."RECEPCIONTRANSACCION" 
   (    "ID_TRANSMISION" NUMBER, 
    "ERROR" NUMBER DEFAULT 0, 
    "ID_MENSAJE" VARCHAR2(50 BYTE)) 
--   ) SEGMENT CREATION IMMEDIATE 
/*  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Table TIPOMENSAJE
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."TIPOMENSAJE" 
   (    "CODIGO" VARCHAR2(4 BYTE), 
    "DESCRIPCION" VARCHAR2(200 BYTE)) 
--   ) SEGMENT CREATION IMMEDIATE 
/*  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Table TRANSACCION
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."TRANSACCION" 
   (    "ID_MENSAJE" VARCHAR2(50 BYTE), 
    "TIPO_MENSAJE" VARCHAR2(5 BYTE), 
    "TIPO_DOCUMENTO" VARCHAR2(5 BYTE), 
    "NUMERO_DOCUMENTO" VARCHAR2(50 BYTE), 
    "ID_TRANSMISION" NUMBER, 
    "EBXML" CLOB, 
    "MENSAJEXML" CLOB, 
    "FECHA_PRIMERA_LECTURA" DATE, 
    "CANTIDAD_LECTURAS" NUMBER DEFAULT 0, 
    "ESTADO" NUMBER DEFAULT 1, 
    "FECHA_ULTIMA_LECTURA" DATE, 
    "FECHA_CONFIRMACION" DATE, 
    "TAMANO_ADJUNTOS" NUMBER) 
--   ) SEGMENT CREATION IMMEDIATE 
/*  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" 
 LOB ("EBXML") STORE AS SECUREFILE (TABLESPACE MT_LOB)
--  TABLESPACE "MT_LOB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  --STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  --PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MENSAJEXML") STORE AS SECUREFILE (TABLESPACE MT_LOB);
 --(
---  TABLESPACE "MT_LOB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
--  NOCACHE LOGGING 
 -- STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 -- PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "MTOBJ"."TRANSACCION"."ESTADO" IS '1. PENDIENTE DE CONFIRMACION, 2. CONFIRMADA SIN ERROR, 3. CONFIRMADA CON ERROR';
--------------------------------------------------------
--  DDL for Table TRANSMISION_ENTRADA
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."TRANSMISION_ENTRADA" 
   (    "VE_ID" NUMBER, 
    "ID_ENTIDAD" NUMBER, 
    "TIPO_MENSAJE" VARCHAR2(20 BYTE), 
    "TIPO_DOCUMENTO" VARCHAR2(20 BYTE), 
    "NUMERO_DOCUMENTO" VARCHAR2(20 BYTE), 
    "ID_MENSAJE" VARCHAR2(50 BYTE), 
    "FECHA_RECEPCION" DATE, 
    "XML" CLOB) 
--   ) SEGMENT CREATION IMMEDIATE 
/*  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" 
 LOB ("XML") STORE AS SECUREFILE (TABLESPACE MT_LOB); 
 --(
/*  TABLESPACE "MT_LOB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;*/
--------------------------------------------------------
--  DDL for Table TRANSMISION_SALIDA
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."TRANSMISION_SALIDA" 
   (    "ID_MENSAJE" VARCHAR2(50 BYTE), 
    "FECHA_HORA_RESPUESTA" DATE, 
    "FECHA_HORA_SOLICITUD" DATE, 
    "HAY_FALLA" NUMBER(*,0), 
    "DESCRIPCION_FALLA" VARCHAR2(100 BYTE), 
    "NOMBRE_OPERACION" VARCHAR2(50 BYTE), 
    "NOMBRE_USUARIO" VARCHAR2(20 BYTE), 
    "VERSION" VARCHAR2(20 BYTE), 
    "TIEMPO_RESPUESTA" NUMBER) 
--   ) SEGMENT CREATION IMMEDIATE 
/*  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Table TX_ENTIDAD
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."TX_ENTIDAD" 
   (    "ID_ENTIDAD" NUMBER, 
    "DESCRIPCION" VARCHAR2(50 BYTE), 
    "COLOR" VARCHAR2(100 BYTE), 
    "ESTADO" CHAR(1 BYTE)) 
--   ) SEGMENT CREATION IMMEDIATE 
/*  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Table TX_PARAMETRO
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."TX_PARAMETRO" 
   (    "CODIGO" NUMBER, 
    "TIPO_PARAMETRO" VARCHAR2(20 BYTE), 
    "VALOR_PARAMETRO" VARCHAR2(50 BYTE), 
    "DESC_PARAMETRO" VARCHAR2(150 BYTE)) 
--   ) SEGMENT CREATION IMMEDIATE 
/*  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "MTOBJ"."USUARIO" 
   (    "NOMBRE_USUARIO" VARCHAR2(20 BYTE), 
    "ID_ENTIDAD" NUMBER) 
--   ) SEGMENT CREATION IMMEDIATE 
/*  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_LOB" ;
--------------------------------------------------------
--  DDL for Sequence ENTIDADMANTENIMIENTO_SEQ
--------------------------------------------------------

CREATE SEQUENCE MTOBJ.ENTIDADMANTENIMIENTO_SEQ
  INCREMENT BY 1
  START WITH 21
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCYCLE
  NOORDER
  CACHE 20;

--   CREATE SEQUENCE  "MTOBJ"."ENTIDADMANTENIMIENTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 120 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Index NOTIFICACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."NOTIFICACION_PK" ON "MTOBJ"."TRANSMISION_ENTRADA" ("VE_ID", "ID_ENTIDAD") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index ENTIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."ENTIDAD_PK" ON "MTOBJ"."ENTIDAD" ("ID_ENTIDAD") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index TRANSACCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."TRANSACCION_PK" ON "MTOBJ"."TRANSACCION" ("ID_TRANSMISION") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index CONFIGURACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."CONFIGURACION_PK" ON "MTOBJ"."CONFIGURACION" ("LLAVE") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index SOLICITUDENTIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."SOLICITUDENTIDAD_PK" ON "MTOBJ"."TRANSMISION_SALIDA" ("ID_MENSAJE") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index TX_ENTIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."TX_ENTIDAD_PK" ON "MTOBJ"."TX_ENTIDAD" ("ID_ENTIDAD") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index PERIODO_MONITOREO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."PERIODO_MONITOREO_PK" ON "MTOBJ"."PERIODO_MONITOREO" ("HORA") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index RECEPCIONTRANSACCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."RECEPCIONTRANSACCION_PK" ON "MTOBJ"."RECEPCIONTRANSACCION" ("ID_TRANSMISION") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index TIPOMENSAJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."TIPOMENSAJE_PK" ON "MTOBJ"."TIPOMENSAJE" ("CODIGO") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."USUARIO_PK" ON "MTOBJ"."USUARIO" ("NOMBRE_USUARIO") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index ENTIDADMANTENIMIENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MTOBJ"."ENTIDADMANTENIMIENTO_PK" ON "MTOBJ"."ENTIDADMANTENIMIENTO" ("ID_ENTIDAD_MANTENIMIENTO") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Index TX_PARAMETRO_PK
--------------------------------------------------------
--DROP INDEX MTOBJ.TX_PARAMETRO_PK;

--  CREATE UNIQUE INDEX "MTOBJ"."TX_PARAMETRO_PK" ON "MTOBJ"."TX_PARAMETRO" ("CODIGO") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
--  TABLESPACE "MT_DAT" ;
--------------------------------------------------------
--  DDL for Procedure HABILITAR_TRANSMISIONES
--------------------------------------------------------
--set define off;

--------------------------------------------------------
--  Constraints for Table PERIODO_MONITOREO
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."PERIODO_MONITOREO" ADD CONSTRAINT "PERIODO_MONITOREO_PK" PRIMARY KEY ("HORA");
--  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
/*  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
--  TABLESPACE "MT_DAT"  ENABLE;
  ALTER TABLE "MTOBJ"."PERIODO_MONITOREO" MODIFY ("HORA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSMISION_SALIDA
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."TRANSMISION_SALIDA" ADD CONSTRAINT "TRANSMISIONSALIDA_PK" PRIMARY KEY ("ID_MENSAJE");
--  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
/*  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
 -- TABLESPACE "MT_DAT"  ENABLE;
  ALTER TABLE "MTOBJ"."TRANSMISION_SALIDA" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_SALIDA" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_SALIDA" MODIFY ("NOMBRE_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_SALIDA" MODIFY ("DESCRIPCION_FALLA" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_SALIDA" MODIFY ("HAY_FALLA" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_SALIDA" MODIFY ("FECHA_HORA_SOLICITUD" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_SALIDA" MODIFY ("FECHA_HORA_RESPUESTA" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_SALIDA" MODIFY ("ID_MENSAJE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECEPCIONTRANSACCION
--------------------------------------------------------
--ALTER TABLE "MTOBJ"."RECEPCIONTRANSACCION" DROP CONSTRAINT RECEPCIONTRANSACCION_PK
ALTER TABLE MTOBJ.RECEPCIONTRANSACCION ADD CONSTRAINT RECEPCIONTRANSACCION_PK PRIMARY KEY ("ID_TRANSMISION");
--  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
/*  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  --TABLESPACE "MT_DAT" ENABLE;
  ALTER TABLE "MTOBJ"."RECEPCIONTRANSACCION" MODIFY ("ID_MENSAJE" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."RECEPCIONTRANSACCION" MODIFY ("ERROR" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."RECEPCIONTRANSACCION" MODIFY ("ID_TRANSMISION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TX_PARAMETRO
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."TX_PARAMETRO" ADD CONSTRAINT "TX_PARAMETRO_PK" PRIMARY KEY ("CODIGO");
--  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
/*  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
  --TABLESPACE "MT_DAT"  ENABLE;
  ALTER TABLE "MTOBJ"."TX_PARAMETRO" MODIFY ("DESC_PARAMETRO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TX_PARAMETRO" MODIFY ("VALOR_PARAMETRO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TX_PARAMETRO" MODIFY ("TIPO_PARAMETRO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TX_PARAMETRO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTIDADMANTENIMIENTO
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."ENTIDADMANTENIMIENTO" ADD CONSTRAINT "ENTIDADMANTENIMIENTO_PK" PRIMARY KEY ("ID_ENTIDAD_MANTENIMIENTO");
--  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
/*  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)*/
--  TABLESPACE "MT_DAT"  ENABLE;
  ALTER TABLE "MTOBJ"."ENTIDADMANTENIMIENTO" MODIFY ("ID_ENTIDAD_MANTENIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."ENTIDADMANTENIMIENTO" MODIFY ("FECHA_FIN" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."ENTIDADMANTENIMIENTO" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."ENTIDADMANTENIMIENTO" MODIFY ("ID_ENTIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTIDAD
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."ENTIDAD" ADD CONSTRAINT "ENTIDAD_PK" PRIMARY KEY ("ID_ENTIDAD");
--  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--  TABLESPACE "MT_DAT"  ENABLE;
  ALTER TABLE "MTOBJ"."ENTIDAD" MODIFY ("ID_ENTIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TX_ENTIDAD
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."TX_ENTIDAD" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TX_ENTIDAD" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TX_ENTIDAD" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TX_ENTIDAD" MODIFY ("ID_ENTIDAD" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TX_ENTIDAD" ADD CONSTRAINT "TX_ENTIDAD_PK" PRIMARY KEY ("ID_ENTIDAD");
--  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOMENSAJE
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."TIPOMENSAJE" ADD CONSTRAINT "TIPOMENSAJE_PK" PRIMARY KEY ("CODIGO");
--  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--  TABLESPACE "MT_DAT"  ENABLE;
  ALTER TABLE "MTOBJ"."TIPOMENSAJE" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TIPOMENSAJE" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSMISION_ENTRADA
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."TRANSMISION_ENTRADA" ADD CONSTRAINT "TRASMISIONENTRADA_PK" PRIMARY KEY ("VE_ID", "ID_ENTIDAD");
/*  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_DAT"  ENABLE;*/
  ALTER TABLE "MTOBJ"."TRANSMISION_ENTRADA" MODIFY ("FECHA_RECEPCION" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_ENTRADA" MODIFY ("ID_MENSAJE" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_ENTRADA" MODIFY ("NUMERO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_ENTRADA" MODIFY ("TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_ENTRADA" MODIFY ("TIPO_MENSAJE" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_ENTRADA" MODIFY ("ID_ENTIDAD" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSMISION_ENTRADA" MODIFY ("VE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACCION
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."TRANSACCION" ADD CONSTRAINT "TRANSACCION_PK" PRIMARY KEY ("ID_TRANSMISION");
/*  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_DAT"  ENABLE;*/
  ALTER TABLE "MTOBJ"."TRANSACCION" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSACCION" MODIFY ("CANTIDAD_LECTURAS" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSACCION" MODIFY ("ID_TRANSMISION" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSACCION" MODIFY ("NUMERO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSACCION" MODIFY ("TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSACCION" MODIFY ("TIPO_MENSAJE" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."TRANSACCION" MODIFY ("ID_MENSAJE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("NOMBRE_USUARIO");
/*  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_DAT"  ENABLE;*/
  ALTER TABLE "MTOBJ"."USUARIO" MODIFY ("ID_ENTIDAD" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."USUARIO" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONFIGURACION
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."CONFIGURACION" ADD CONSTRAINT "CONFIGURACION_PK" PRIMARY KEY ("LLAVE");
/*  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_DAT"  ENABLE;*/
  ALTER TABLE "MTOBJ"."CONFIGURACION" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "MTOBJ"."CONFIGURACION" MODIFY ("LLAVE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ENTIDADMANTENIMIENTO
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."ENTIDADMANTENIMIENTO" ADD CONSTRAINT "ENTIDADMANTENIMIENTO_FK" FOREIGN KEY ("ID_ENTIDAD")
      REFERENCES "MTOBJ"."ENTIDAD" ("ID_ENTIDAD") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECEPCIONTRANSACCION
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."RECEPCIONTRANSACCION" ADD CONSTRAINT "RECEPCIONTRANSACCION_FK1" FOREIGN KEY ("ID_MENSAJE")
      REFERENCES "MTOBJ"."TRANSMISION_SALIDA" ("ID_MENSAJE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACCION
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."TRANSACCION" ADD CONSTRAINT "TRANSACCION_FK1" FOREIGN KEY ("ID_MENSAJE")
      REFERENCES "MTOBJ"."TRANSMISION_SALIDA" ("ID_MENSAJE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSMISION_ENTRADA
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."TRANSMISION_ENTRADA" ADD CONSTRAINT "TRASMISIONENTRADA_FK" FOREIGN KEY ("ID_MENSAJE")
      REFERENCES "MTOBJ"."TRANSMISION_SALIDA" ("ID_MENSAJE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSMISION_SALIDA
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."TRANSMISION_SALIDA" ADD CONSTRAINT "TRANSMISIONSALIDA_FK" FOREIGN KEY ("NOMBRE_USUARIO")
      REFERENCES "MTOBJ"."USUARIO" ("NOMBRE_USUARIO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "MTOBJ"."USUARIO" ADD CONSTRAINT "USUARIO_FK1" FOREIGN KEY ("ID_ENTIDAD")
      REFERENCES "MTOBJ"."ENTIDAD" ("ID_ENTIDAD") ON DELETE CASCADE ENABLE;

